### ISSUE TITLE
some errors when try to run inference on cameras

### ISSUE THREAD

**Issue by liangxiao05** [wei-tim/YOWO#10]
@okankop @wei-tim First of all thanks for open source and  your great work , I had few queries when I try to run inference on cameras.

1.a little error need to be fixed.
 https://github.com/wei-tim/YOWO/blob/master/model.py#L73 
`nn.Conv2d(1024, 5*(opt.n_classes+4+1), kernel_size=1, bias=False)`
should be
`nn.Conv2d(1024, 5*(int(opt.n_classes)+4+1), kernel_size=1, bias=False)`
2.In the dataloader 
https://github.com/wei-tim/YOWO/blob/master/dataset.py#L63
```
        # (self.duration, -1) + self.shape = (8, -1, 224, 224)
        clip = torch.cat(clip, 0).view((self.clip_duration, -1) + self.shape).permute(1, 0, 2, 3)
```
the input image clip is a 4-dims tensor with shape (3,D,H,W) .
However,when model forward,the last frame of the clip is sliced from the input by  input[:, :, -1, :, :]
seems to be that the clip is a 5-dims tensor with shape (batch_size,3,D,H,W)
https://github.com/wei-tim/YOWO/blob/master/model.py#L81,
```
    def forward(self, input):
        x_3d = input # Input clip
        x_2d = input[:, :, -1, :, :] # Last frame of the clip that is read
```

**Comment by 17702513221** [comment]
Can you share your code

**Comment by liangxiao05** [comment]
> Can you share your code

As the reasons above, there'are some errors when model forward and the code can't work , and I can't test whether the schedule is right .When I finished this,I'm glad to share.

**Comment by okankop** [comment]
Hi @liangxiao05 @17702513221, if you receive errors at inference, it is most probably due to the torch version you are using. The code in this repo is developed with PyTorch version 1.3.0, and all the pretrained models provided are produced using the repo as it is.

Either you need to update your PyTorch version, or you need to make small modifications as @liangxiao05 did!

**Comment by okankop** [comment]
I believe the issue is resolved!

**Comment by abhigoku10** [comment]
@liangxiao05  can you share the inference pipeline code to run on cameras?

**Comment by okankop** [comment]
@abhigoku10 @liangxiao05 @17702513221 The code is updated. You can use [test_video_ava.py](https://github.com/wei-tim/YOWO/blob/master/test_video_ava.py) to get detections on any test video.
