### ISSUE TITLE
How to run the model on webcam

### ISSUE THREAD

**Issue by bilel-bj** [wei-tim/YOWO#12]
I want to test the code on the webcam or on a chosen video to generate videos like the shown the folder examples.
How to do that?

**Comment by okankop** [comment]
@bilel-bj  you can follow the test procedure as in https://github.com/wei-tim/YOWO/blob/master/train.py for inference. However, you need to write a script to capture frames from the webcam though.

**Comment by okankop** [comment]
I believe issue is resolved!

**Comment by okankop** [comment]
@bilel-bj The code is updated. You can use test_video_ava.py to get detections on any test video. Just modify video frame reading part to read frames from webcam.
