### ISSUE TITLE
How is it supposed to do inference?

### ISSUE THREAD

**Issue by betegon** [wei-tim/YOWO#14]
Hi, 

I have been trying to do inference on a video and I found myself lost. I have read that it is necessary to do inference in frames instead of videos, is it true?

Where is the script to run inference?

Thanks you your time,

Miguel.

**Comment by okankop** [comment]
yes, you need to extract frames of the video first. Then you should follow the test procedure as in https://github.com/wei-tim/YOWO/blob/master/train.py for inference.

**Comment by abhigoku10** [comment]
@okankop  we should first train the model rigth for custom dataset ??? is it possible to share pre-trained model which we can use for testing on the video

**Comment by okankop** [comment]
@abhigoku10 my answer above is still valid. Please follow the test procedure as in https://github.com/wei-tim/YOWO/blob/master/train.py for inference.

**Comment by okankop** [comment]
I believe issue is resolved!
