### ISSUE TITLE
There ara no BoundingBox and BoundingBoxes package

### ISSUE THREAD

**Issue by BChunlei** [wei-tim/YOWO#16]
In YOWO/evaluation/Object-Detection-Metrics/pascalvoc.py file,
from BoundingBox import BoundingBox
from BoundingBoxes import BoundingBoxes
but no BoundingBox and BoundingBoxes package

**Comment by BChunlei** [comment]
and also 
from Evaluator import *
from utils import BBFormat
in pascalvoc.py file

**Comment by okankop** [comment]
Sorry for the inconvenience. Necessary files are added. Please pull the updated repo.
