### ISSUE TITLE
no training dataset annotations

### ISSUE THREAD

**Issue by linzhirui1992** [wei-tim/YOWO#18]
I download the dataset annotations from the [link](https://www.dropbox.com/sh/16jv2kwzom1pmlt/AABL3cFWDfG5MuH9PwnjSJf0a?dl=0) in README, but I find that there are only testing dataset annotations, no annotations of tranlist.txt. Can you check it out ? Thank you.

**Comment by okankop** [comment]
Training and testing annotations are available under respective annotations folders. Please download and check again.

**Comment by okankop** [comment]
I believe the issue is resolved

**Comment by lg12170226** [comment]
@linzhirui1992 @okankop i download from baiduyunpan.there are  trainlist.txt and testlist.txt,but the groundtruths_ucf.zip have the txt num is 137557 ,which is the same as testlist.txt,no train dataset annotations.

**Comment by linzhirui1992** [comment]
> @linzhirui1992 @okankop i download from baiduyunpan.there are trainlist.txt and testlist.txt,but the groundtruths_ucf.zip have the txt num is 137557 ,which is the same as testlist.txt,no train dataset annotations.

me too

**Comment by okankop** [comment]
@lg12170226 @linzhirui1992 The annotations in groundtruths_ucf.zip is only used at calculating the Frame_mAP scores. This is why there is no training annotations there. Training annotations can be downloaded from the dataset sources.

**Comment by okankop** [comment]
Please use the following steps to use the codes in the repo. These steps have recently been validated by another user of the repo!

**FOR UCF DATASET:**

**For Training**

1. Download ucf dataset, unzip file. Rename the datafolder as ‘ucf24’.
2. Create a new folder by the name of ‘datasets’. Put the above renamed ‘ucf24’ folder inside the datasets folder.
3. Download code from GitHub page. The code folder is called YOWO
4. Open cfg/ucf24.data’ in the YOWO folder.  Update address of the base, training and validation dataset
5. Download ‘trainlist.txt’ and ‘testlist.txt’ files and put it inside the ‘ucf24’ folder created in step-1.
6. Create a folder called ‘weights’ in the YOWO folder. 
7. Download pre-trained yolo weights, details given the GitHub page, and put it in the folder created in step-6.
8. Download ‘resnext-101-kinetics.pth’ from the GitHub page and put in the ‘weights’ folder created in step -6.


**For Validation**
1. Go to YOWO/evaluations/Object-Detection-Metrics
2. Unzip the file ‘groundtruths_ucf.zip’
3. Go back to the YOWO folder. Create a folder called ‘ucf_detections/detections_0’. Keep creating multiple subdirectories ‘detections_n’ for n = 0,1,2,3….. for further tasks.
4. Run validation using the command 

Run both training and validating model using the script:
`$ sh run_ucf101-24.sh`

1. Change the ‘detection_n’ portion in the script file for multiple validation tasks.
`python ./evaluation/Object-Detection-Metrics/pascalvoc.py --gtfolder groundtruths_ucf --detfolder ../../ucf_detections/detections_0`
