### ISSUE TITLE
When can you opensource YOWO？hah

### ISSUE THREAD

**Issue by wsakobe** [wei-tim/YOWO#2]

**Comment by Amazingren** [comment]
我也在等

**Comment by 17702513221** [comment]
你们可以先去试试SlowFast，是facebook开源的行为识别

**Comment by Amazingren** [comment]
> 你们可以先去试试SlowFast，是facebook开源的行为识别
大概看了一下slow-fast的论文，算力差太远，玩不起

**Comment by okankop** [comment]
Sorry for the delay!

**Comment by tomatowithpotato** [comment]
> 你们可以先去试试SlowFast，是facebook开源的行为识别

大佬，有没有试过把YOWO里的resnext3d换成slowfast？
