### ISSUE TITLE
Question regarding the paper

### ISSUE THREAD

**Issue by usamahjundia** [wei-tim/YOWO#26]
Hi! Thanks for open sourcing the implementation. This is my first paper i read in spatio-temporal action localization.

I am aware that this might be not the best place to ask about the paper, but i cant seem to find other ways to contact (i.e, email address) in the paper so i decided to make an issue.

So i've read:
1.  the action tube paper, and 
2. i also read issue #21, and
3. seeing that in the paper, the classification is associated with each bounding boxes 

And from that, i make 1 conclusion :
**That the whole linking thing is all about associating detections of one or more actions in one frame into one or more actions in subsequent frames**

So does this mean it is possible for multiple actions of different classes to be detected at once?

I am sorry if this is such a silly question, i can't seem to find the statement above being explicitly stated.

**Comment by okankop** [comment]
Hi @usamahjundia 
Yes, linking is just associating frame level detections over the complete video to create action tubes. Again yes, it is  possible for multiple actions of different classes to be detected at once.

**Comment by usamahjundia** [comment]
That clear things up, many thanks!
