### ISSUE TITLE
Some puzzle about CAFM

### ISSUE THREAD

**Issue by dagongji10** [wei-tim/YOWO#28]
In the paper chapter3.1.3, formula (4): ![](http://latex.codecogs.com/gif.latex?\\Bold{F}^{'}=M^T\cdot{F})，why M is transpose ?
In my opinion, ![](http://latex.codecogs.com/gif.latex?\\Bold{M}_{ij}) is j-th feature's impact on i-th feature, so after including this impact, the i-th feature should be ![](http://latex.codecogs.com/gif.latex?\\Bold{F}_{i}^{'}=M_{i1}\cdot{F_1}+M_{i2}\cdot{F_2}+M_{i3}\cdot{F_3}+\cdots+M_{iC}\cdot{F_C}). And M may needn't transpose.

**Comment by wei-tim** [comment]
@dagongji10 
You are correct, that's a typo. Thanks for your correction.
