### ISSUE TITLE
JHMDB dataset missing labels

### ISSUE THREAD

**Issue by Clarary** [wei-tim/YOWO#30]
Thank you for your open source！
I want to use J-HMDB-21 to train the model. However, from your link [here](http://jhmdb.is.tue.mpg.de/challenge/JHMDB/datasets), I can only get rgb-images but without labels. I wonder if I miss anything or if the link is incorrect.
Hope to get your answer, thanks a lot!

**Comment by okankop** [comment]
You can refer to #25 for the jhmdb labels.

**Comment by Clarary** [comment]
> You can refer to #25 for the jhmdb labels.

Thanks! I have solved it now.
