### ISSUE TITLE
[discuss] Can you share the extra tricks you use?

### ISSUE THREAD

**Issue by yzfly** [wei-tim/YOWO#32]
I have train yowo on ucf101-24 and jhmdb21 datasets, the best frame_mAP I can achieve is 84.3% and 
70.9% for UCF101-24 and J-HMDB-21, which are far behind the accuracy of your report. And I see following words:

NOTE: With some extra tricks, YOWO achieves 87.5% and 76.7% frame_mAP for UCF101-24 and J-HMDB-21 datasets, respectively.

Can you share the extra tricks you use?

**Comment by okankop** [comment]
Firsf we have applied "multi rate downsampling" as temporal augmentation for the training. That gives the main performance increase. For the jhmdb-21 training, we also froze the 2d-backbone except for the final conv layer.

**Comment by yzfly** [comment]
> First, we have applied "multi rate downsampling" as temporal augmentation for the training. That gives the main performance increase. Secend, for the jhmdb-21 training, we also froze the 2d-backbone except for the final conv layer.

Thank you so much!
