### ISSUE TITLE
Save checkpoints while training

### ISSUE THREAD

**Issue by nkise** [wei-tim/YOWO#34]
Does the model saving checkpoints at the training? It seems that I need to start evaluation for it...

**Comment by wei-tim** [comment]
@nkise 
Hi,
pls check the train.py script. You will find how the checkpoints are saved during training :-)

**Comment by nkise** [comment]
Sorry, I thought it was saving after all epochs 😅🤦
P.S. Could you please provide

> @nkise
> Hi,
> pls check the train.py script. You will find how the checkpoints are saved during training :-)

 Sorry, I thought it was saving after all epochs 😅🤦
P.S. Could you please provide some hints for training on own dataset? For example, how to deal with low localization and how fast is converges?

**Comment by wei-tim** [comment]
@nkise 
If you read the code carefully you will find that after each epoch of training, checkpoints for the best model will be updated ;-)

As for training on your own dataset, it depends on actual circumstances. If some classes in your dataset are already in UCF101-24 or J-HMDB-21, it would be easier and faster to converge while finetuning the model. If your dataset is small, from my experience, you can freeze some parts of the whole network to avoid overfitting problem.
