### ISSUE TITLE
RuntimeError: 

### ISSUE THREAD

**Issue by 17854224426** [wei-tim/YOWO#36]
When I train ucf24, I get the following error：

Traceback (most recent call last):
  File "train.py", line 322, in <module>
    train(epoch)
  File "train.py", line 180, in train
    loss = region_loss(output, target)
  File "/home/chase/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chase/YOWO/region_loss.py", line 229, in forward
    nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "/home/chase/YOWO/region_loss.py", line 126, in build_targets
    iou = bbox_iou(gt_box, pred_box, x1y1x2y2=False) # best_iou
  File "/home/chase/YOWO/utils.py", line 72, in bbox_iou
    cw = w1 + w2 - uw
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.FloatTensor for argument #3 'other'

**Comment by wei-tim** [comment]
@17854224426 
Hi, 

I have not met such a problem before, but it seems because your Pytorch version is different from ours. I think you can simply modify the datatype of tensors that result in this problem.

**Comment by 17854224426** [comment]
@wei-tim 
Thanks for your answer，it's ok now

**Comment by Griffintaur** [comment]
@wei-tim I try running the video map for Jhmdb with the provided pretrained jhmdb model but its throwing the following error?
I will appreciate your help on this.
`
 

> File "video_mAP.py", line 338, in <module>
>     video_mAP_jhmdb()
>   File "video_mAP.py", line 331, in video_mAP_jhmdb
>     print(evaluate_videoAP(gt_videos, detected_boxes, CLASSES, iou_th, True))
>   File "YOWO/core/eval_results.py", line 250, in evaluate_videoAP
>     ap = video_ap_one_class(gt, pred_cls, iou_thresh, bTemporal, cls_len)
>   File "YOWO/core/eval_results.py", line 161, in video_ap_one_class
>     iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
>   File "YOWO/core/eval_results.py", line 161, in <listcomp>
>     iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
>   File "YOWO/core/utils.py", line 198, in iou3dt
>     tmin = max(b1[0,0], b2[0,0])
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

`
