### ISSUE TITLE
Training and Inference

### ISSUE THREAD

**Issue by abhigoku10** [wei-tim/YOWO#4]
@okankop @wei-tim  First of all thnaks for open sourcing your work and doing a great work , i had few queries 
1. can we run the inference pipeline on CPU 
2. can we add the architectures like efficientnet ,centernet retinanet to ur 3dCNN backbone 
3. to train it on the custom dataset what is the resolution required 
4. have you tested this model on real time video and what is ur fb on this 

thanks in advance

**Comment by wei-tim** [comment]
@abhigoku10 
Hi, thanks for your interest in our project.

1. The model can be run on CPU as long as the PC has sufficient RAM.
2. Definitely. As introduced in our paper, we aim to make the backbone replaceable with different choices. For architectures with FPN (like RetinaNet) we didn't test whether they work similarly as 2D case, but I think it's a very interesting topic. 
3. We trained our model with 224x224 images.
4. Our inference model would work on videos and is able to recognize actions when the performed actions do not diverge too much from the datasets. And our model is based on YOLOv2, which might be not so good at detecting tiny persons, in such cases, the results are kind of unsatisfying.

**Comment by Byronnar** [comment]
> @abhigoku10
> Hi, thanks for your interest in our project.
> 
> 1. The model can be run on CPU as long as the PC has sufficient RAM.
> 2. Definitely. As introduced in our paper, we aim to make the backbone replaceable with different choices. For architectures with FPN (like RetinaNet) we didn't test whether they work similarly as 2D case, but I think it's a very interesting topic.
> 3. We trained our model with 224x224 images.
> 4. Our inference model would work on videos and is able to recognize actions when the performed actions do not diverge too much from the datasets. And our model is based on YOLOv2, which might be not so good at detecting tiny persons, in such cases, the results are kind of unsatisfying.

Thanks for your projects! 
How should I do to test with a video and get the detection results?

**Comment by wei-tim** [comment]
@Byronnar 

Hi,
thanks for your interest in our project.
You can follow the validation procedure and get predictions of bounding boxes as well as action labels.

**Comment by okankop** [comment]
I believe the issue is resolved!
