### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by 17854224426** [wei-tim/YOWO#5]
The datastet annotations and pre-trained models can’t be downloaded. Can anyone share it?

Thanks！

**Comment by 17854224426** [comment]
3041622569@qq.com

**Comment by wei-tim** [comment]
@17854224426 

All materials are available in Baiduyun Disk:
https://pan.baidu.com/s/1yaOYqzcEx96z9gAkOhMnvQ
with password 95mm

**Comment by abhigoku10** [comment]
@wei-tim not able to access the files , is it possible to share it on google drive
