### ISSUE TITLE
abount backbone2d

### ISSUE THREAD

**Issue by xidaoliang** [wei-tim/YOWO#50]
Why don't you use yolov3 or yolov3 tiny as backbone2d?   Backbone2d network can be replaced with them?

**Comment by okankop** [comment]
Yes, more ablation study can be made also with different 2D-bacbones. From our observation, what is critical for action localization is the temporal information accumulation. That is why we have in general used much stronger 3D-backbones compared to 2D-backbone. But, we have written the code modular and easy to switch backbones. You can try different 2d-backbones and let us know the results :)

**Comment by xidaoliang** [comment]
Thank you very much for your reply
