### ISSUE TITLE
First of all thnaks for open sourcing your work and doing a great work. should I do to test with a video and get the detection results?

### ISSUE THREAD

**Issue by yangzhegithub** [wei-tim/YOWO#6]

**Comment by wei-tim** [comment]
@yangzhegithub 

Hi,
thanks for your interest in our work.
You can follow the validation procedure to get detection result, which contains predicted bounding box coordinates and labels in each frame. After that, you can try many tools like OpenCV to visualize them in the input video.

**Comment by yangzhegithub** [comment]
@wei-tim thanks.  I will try ..

**Comment by okankop** [comment]
I believe the issue is resolved!
