### ISSUE TITLE
Frame mAP on UCF24

### ISSUE THREAD

**Issue by alphadadajuju** [wei-tim/YOWO#75]
Thank you for sharing your amazing work (I see that you even verified YOWO's performance on AVA recently)!

I do have some questions related to how you evaluated UCF-24's frame mAP, and was hoping you could help me clarify.
1. It appears that YOWO's frame mAP is evaluated using "testlist.txt" provided along other annotation. However, testlist.txt is temporally trimmed (only containing frames that have action groundtruths). Does it mean that to calculate frame mAP, you do not consider frames without action groundtruths?
2. If non-groundtruth frames are left out for evaluation, then wouldn't the computed frame mAP be higher, as the chance of false positives has been greatly reduced? (other studies such as ACT seemed to consider this false positives into account when evaluating frame mAP).

(It may be the case that I didn't fully grasp your code ... please don't hesitate to correct me if I made a mistake!)
Thank you again.

**Comment by okankop** [comment]
@alphadadajuju yes you are right. To calculte f-mAP you need ground truths, such that you can calculate the IoU with ground truths and predictions. Therefore, we have calculated f-mAP where we have annottions. However, for video-mAP we have uses untrimmed videos. 

For AVA dataset, only frame-mAP is used for evaluation and annotations are provided for sampling rate of 1 Hz.

**Comment by alphadadajuju** [comment]
Thank you for your clarifications!

**Comment by Griffintaur** [comment]
@okankop I tried to run the pretrained JHMDB-21 model to get the Video-map for Jhmdb. I am getting `0` precision for all classes of the JHMDB-21 dataset. Can you have a look on that?
I will really appreciate your help on this.
