### ISSUE TITLE
how to input a video and outputs a video in the format of ava

### ISSUE THREAD

**Issue by xuhui1994** [wei-tim/YOWO#76]

**Comment by okankop** [comment]
Please check the file [test_video_ava.py](https://github.com/wei-tim/YOWO/blob/master/test_video_ava.py)

**Comment by xuhui1994** [comment]
Thank your reply, I had been checked test_video_ava.py before. This code just outputs images whose size is 224x224. I wanna to get the predict video &nbsp;whose resolution is same as test video (for example,1920x1080),rather than 224x224 images&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wei-tim/YOWO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wei-tim/YOWO] how to input a video and outputs a video in the format of ava (#76)





 
Closed #76.

**Comment by okankop** [comment]
You can resize your video to 224x224 get your predictions and resize these predictions back to 1920x1080.

If you want to use resolution 1920x1080 directly at inference, you need to train the models again with this resolution.
