### ISSUE TITLE
Working on dataset other than humans

### ISSUE THREAD

**Issue by Vishak66** [wei-tim/YOWO#79]
Hello All,

Thank you for all the work done here! I was wondering if this network could work on datasets other than humans. For eg: can I have a custom dataset with cars and humans and their associated actions. Will this network be able to predict two completely different objects and their actions? Thank you

**Comment by okankop** [comment]
Yes you can definitely use YOWO for the tasks similar to what you explained such as MEVA dataset.

**Comment by Vishak66** [comment]
Thank yo for your reply. So to prepare that dataset, I can construct something like the AVA dataset, but with new bounding boxes for the different objects and their actions right?

**Comment by okankop** [comment]
@Vishak66 Exactly!
