### ISSUE TITLE
about own data 

### ISSUE THREAD

**Issue by lrhjw** [wei-tim/YOWO#8]
First of all ,Thanks for your project ，I am interested in this project,please show your label If it's convenient for you

**Comment by wei-tim** [comment]
@lrhjw 

Hi,
links for datasets and corresponding annotations are provided in README file, you can download them freely.

**Comment by lrhjw** [comment]
@wei-tim
Thanks  ,I just found there's a problem with my network to enter the links ,now   I know the reason . thank you !

**Comment by wei-tim** [comment]
@lrhjw 
With pleasure ;-)
